<a href="https://colab.research.google.com/github/Kamalsharma358/ML-LAB/blob/main/ML_LabAssignment1_ipyn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


                                                       Question : 1

(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]

print(reversed_arr)

[5 4 6 3 2 1]



(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods

In [ ]:
import numpy as np

array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flattened_array1 = array1.flatten()

print(flattened_array1)

[1 2 3 2 4 5 1 2 3]


(c) Compare the following numpy arrays:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])


comparison = np.equal(arr1, arr2)


arrays_equal = np.array_equal(arr1, arr2)

print("Element-wise comparison:\n", comparison)
print("Are the arrays equal?", arrays_equal)

Element-wise comparison:
 [[ True  True]
 [ True  True]]
Are the arrays equal? True


(d) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])


In [ ]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
unique, counts = np.unique(x, return_counts=True)
most_frequent_value = unique[np.argmax(counts)]
indices = np.where(x == most_frequent_value)[0]

print("Most frequent value:", most_frequent_value)
print("Indices of the most frequent value:", indices)

Most frequent value: 1
Indices of the most frequent value: [0 5 7 8 9]


In [ ]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
unique, counts = np.unique(y, return_counts=True)
most_frequent_value = unique[np.argmax(counts)]
indices = np.where(y == most_frequent_value)[0]

print("Most frequent value:", most_frequent_value)
print("Indices of the most frequent value:", indices)

Most frequent value: 1
Indices of the most frequent value: [0 1 2]


(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find
i. Sum of all elements
ii. Sum of all elements row-wise
iii. Sum of all elements column-wise

In [ ]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')


total_sum = np.sum(gfg)


row_sum = np.sum(gfg, axis=1)


col_sum = np.sum(gfg, axis=0)

print("Sum of all elements:", total_sum)
print("Sum of all elements row-wise:", row_sum)
print("Sum of all elements column-wise:", col_sum)

Sum of all elements: 45
Sum of all elements row-wise: [[14]
 [16]
 [15]]
Sum of all elements column-wise: [[20  9 16]]


(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find
i. Sum of diagonal elements
ii. Eigen values of matrix
iii. Eigen vectors of matrix
iv. Inverse of matrix
v. Determinant of matrix

In [ ]:
import numpy as np


n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])


sum_diagonal = np.trace(n_array)
print(f"Sum of diagonal elements: {sum_diagonal}")


eigenvalues, eigenvectors = np.linalg.eig(n_array)
print(f"Eigenvalues of the matrix: {eigenvalues}")


print(f"Eigenvectors of the matrix:\n{eigenvectors}")


inverse_matrix = np.linalg.inv(n_array)
print(f"Inverse of the matrix:\n{inverse_matrix}")


determinant = np.linalg.det(n_array)
print(f"Determinant of the matrix: {determinant}")

Sum of diagonal elements: 176
Eigenvalues of the matrix: [98.16835147 28.097044   49.73460452]
Eigenvectors of the matrix:
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of the matrix:
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of the matrix: 137180.0000000001


(g) Multiply the following matrices and also find covariance between matrices using NumPy:
i. p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
ii. p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]
(h) For the matrices: x = np.array([[2, 3

In [ ]:
import numpy as np


p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

product1 = np.dot(p1, q1)
p1_flat = p1.flatten()
q1_flat = q1.flatten()
covariance1 = np.cov(p1_flat, q1_flat)

print("First case:")
print("Matrix multiplication result:\n", product1)
print("Covariance matrix:\n", covariance1)
print()

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

product2 = np.dot(p2, q2)
p2_flat = p2.flatten()
q2_flat = q2.flatten()
covariance2 = np.cov(p2_flat, q2_flat)

print("Second case:")
print("Matrix multiplication result:\n", product2)
print("Covariance matrix:\n", covariance2)

First case:
Matrix multiplication result:
 [[16 19]
 [26 31]]
Covariance matrix:
 [[0.66666667 1.        ]
 [1.         1.66666667]]

Second case:
Matrix multiplication result:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance matrix:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?


In [ ]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

inner_product = np.inner(x, y)


outer_product = np.outer(x, y)


cartesian_product = np.cross(x, y)

print("Inner product:\n", inner_product)
print("Outer product:\n", outer_product)
print("Cartesian product:\n", cartesian_product)

Inner product:
 [[17 52]
 [13 62]]
Outer product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product:
 [[-20   4   7]
 [-84  36  20]]


                                             Question :2

(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])
i. Find element-wise absolute value
ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.
iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row

In [ ]:
import numpy as np

array = np.array([[1, -2, 3], [-4, 5, -6]])


absolute_array = np.abs(array)
print("Element-wise absolute value:\n", absolute_array)


flattened_array = array.flatten()
percentiles_flattened = np.percentile(flattened_array, [25, 50, 75])
print("Percentiles (25th, 50th, 75th) for flattened array:", percentiles_flattened)


percentiles_columns = np.percentile(array, [25, 50, 75], axis=0)
print("Percentiles (25th, 50th, 75th) for each column:\n", percentiles_columns)


percentiles_rows = np.percentile(array, [25, 50, 75], axis=1)
print("Percentiles (25th, 50th, 75th) for each row:\n", percentiles_rows)


mean_flattened = np.mean(flattened_array)
median_flattened = np.median(flattened_array)
std_flattened = np.std(flattened_array)
print("Mean for flattened array:", mean_flattened)
print("Median for flattened array:", median_flattened)
print("Standard Deviation for flattened array:", std_flattened)


mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_columns = np.std(array, axis=0)
print("Mean for each column:", mean_columns)
print("Median for each column:", median_columns)
print("Standard Deviation for each column:", std_columns)


mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_rows = np.std(array, axis=1)
print("Mean for each row:", mean_rows)
print("Median for each row:", median_rows)
print("Standard Deviation for each row:", std_rows)

Element-wise absolute value:
 [[1 2 3]
 [4 5 6]]
Percentiles (25th, 50th, 75th) for flattened array: [-3.5 -0.5  2.5]
Percentiles (25th, 50th, 75th) for each column:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles (25th, 50th, 75th) for each row:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Mean for flattened array: -0.5
Median for flattened array: -0.5
Standard Deviation for flattened array: 3.8622100754188224
Mean for each column: [-1.5  1.5 -1.5]
Median for each column: [-1.5  1.5 -1.5]
Standard Deviation for each column: [2.5 3.5 4.5]
Mean for each row: [ 0.66666667 -1.66666667]
Median for each row: [ 1. -4.]
Standard Deviation for each row: [2.05480467 4.78423336]


(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values

In [ ]:
import numpy as np

a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])


floor_values = np.floor(a)
print("Floor values:", floor_values)

ceiling_values = np.ceil(a)
print("Ceiling values:", ceiling_values)

truncated_values = np.trunc(a)
print("Truncated values:", truncated_values)


rounded_values = np.round(a)
print("Rounded values:", rounded_values)

Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values: [-2. -2. -0.  0.  2.  2.  3.]


                                          Question:3

(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find
i. Sorted array
ii. Indices of sorted array
iii. 4 smallest elements
iv. 5 largest elements

In [ ]:
import numpy as np


array = np.array([10, 52, 62, 16, 16, 54, 453])

sorted_array = np.sort(array)


sorted_indices = np.argsort(array)


smallest_elements = sorted_array[:4]


largest_elements = sorted_array[-5:]

print("Sorted array:", sorted_array)
print("Indices of sorted array:", sorted_indices)
print("4 smallest elements:", smallest_elements)
print("5 largest elements:", largest_elements)

Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find
i. Integer elements only
ii. Float elements only


In [ ]:
import numpy as np


array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])


integer_elements = array[array == array.astype(int)]

float_elements = array[array != array.astype(int)]


print("Integer elements only:", integer_elements)
print("Float elements only:", float_elements)

Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]


                                          Question :4

(a) Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)
(b) Load the saved file into jupyter notebook?

In [ ]:
from PIL import Image
import numpy as np


# rgba_image = Image.open('/content/image_rgb.png')
# rgb_image = rgba_image.convert('RGB')
# rgb_image.save('image_rgb.png')




def img_to_array(path):
    try:
        img = Image.open(path)
        img_array = np.array(img)

        if img.mode == 'RGB':
            np.savetxt('image_rgb.txt', img_array.reshape(-1, 3), fmt='%d')
            print("RGB image array saved as 'image_rgb.txt'")
        elif img.mode == 'L':
            np.savetxt('image_grey.txt', img_array, fmt='%d')
            print("Grayscale image array saved as 'image_grey.txt'")
        else:
            print("Unsupported image mode:", img.mode)
    except Exception as e:
        print("Error:", e)

# Example usage
img_to_array('/content/image_rgb.png')


# b)



# # Assuming the image was saved as image_rgb.txt or image_grey.txt
# img_array_loaded_rgb = np.loadtxt('image_rgb.txt').reshape(-1, 3)
# img_array_loaded_grey = np.loadtxt('image_grey.txt')
# print("Loaded RGB image array:", img_array_loaded_rgb)
# print("Loaded Grey Scale image array:", img_array_loaded_grey)


Error: [Errno 2] No such file or directory: '/content/image_rgb.png'
